[features]
seeds = false
skip-lint = false
[programs.localnet]
review_data = "A1eDpmJYGi8VHwkiqxqztvPK3C3UpSC3LpZ3cE7m6a9"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = "/Users/yudiz/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
